sudo: false
language: python
python:
- '2.7'
env:
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
- provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "dBC9HuH9geZJIDAPcqGtzgJlWKdiAkruYI2jkx5MemQZ4ylfoPuDvS7PSf8n/CCse9hrKdZHIzBaCSGpI+Jv0je+WYz2GKK0cSvte0XUWdvezurECqyMQgYo1jqXn1QWBZ6UhbzOhPmcKJj/doZ55Tc98HwSW1tW4GscfdUUGIA="
- provider: pypi
  server: https://testpypi.python.org/pypi
  on:
    branch: pypi-test
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "dyA0m7fcL+hktvU1a5/AIwJhJ0locRqnjMt3N2McoNjyQwG1v5dGaFWhsLwlO9eHlB+vgn9qdP7LtRCfNwxmCwAD6PfU2Ks2bP0ejzOWGYOMiSv9YBp2HnA8ucCO48ghVv0UuNRL2qIg/6UNOqHvcxUYVEV9IuFg93eRWW1MyJ0="
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v -b $TRAVIS_BRANCH || exit 1
notifications:
  flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
